require('dotenv').config();
const express=require('express'); const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const app=express(); app.use(express.json()); app.use(express.static(path.join(__dirname,'../public')));
const db=path.join(__dirname,'../data/matches.json'); const read=()=>JSON.parse(fs.readFileSync(db,'utf8')); const write=x=>fs.writeFileSync(db,JSON.stringify(x,null,2));
const auth=(req,res,next)=>req.headers.authorization===`Bearer ${process.env.ADMIN_TOKEN}`?next():res.status(401).json({error:'unauthorized'});
app.get('/api/health',(req,res)=>res.json({ok:true,leagueId:Number(process.env.LEAGUE_ID||0)}));
app.get('/api/matches',auth,(req,res)=>res.json(read()));
app.post('/api/matches',auth,(req,res)=>{const m=read(); const id=crypto.randomUUID(); const pass=crypto.randomBytes(4).toString('hex').toUpperCase(); const row={id,status:'queued',name:req.body.name||`Riftline ${id.slice(0,6)}`,password:pass,radiant:req.body.radiant||[],dire:req.body.dire||[],bestOf:req.body.bestOf||3,createdAt:new Date().toISOString()};m.push(row);write(m);res.status(201).json(row)});
app.post('/api/matches/:id/status',auth,(req,res)=>{const m=read(),x=m.find(v=>v.id===req.params.id);if(!x)return res.sendStatus(404);Object.assign(x,req.body,{updatedAt:new Date().toISOString()});write(m);res.json(x)});
app.listen(process.env.PORT||3000,()=>console.log(`Riftline API on :${process.env.PORT||3000}`));
